library(devtools)
use_r("sqrt2")
load_all()
sqrt.2(-3)
check()
use_mit_license("Molin Yue")
use_package("rlang") #default is added to imports
load_all()
library(roxygen2)
use_r("sqrt2")
use_r("log.2")
use_r("f_operator")
document()
build()
